Update astro.yml

diff --git a/.github/workflows/astro.yml b/.github/workflows/astro.yml
--- a/.github/workflows/astro.yml
+++ b/.github/workflows/astro.yml
@@ -29,20 +29,51 @@ env:
   # BUILD_PATH: subfolder
 
 jobs:
+  setup:
+      runs-on: ubuntu-latest
+      steps:
+        - name: Setup Node
+          uses: actions/setup-node@v4
+          with:
+            node-version: "14"
+            cache: pnpm
+            cache-dependency-path: ${{ env.BUILD_PATH }}/pnpm-lock.yaml
+        - name: Install pnpm
+          run: npm install -g pnpm
+        - name: Verify pnpm installation
+          run: pnpm --version
   build:
+    needs: setup
     name: Build
     runs-on: ubuntu-latest
     steps:
-      - name: Setup Node
-        uses: actions/setup-node@v4
-        with:
-          node-version: "20"
-          cache: pnpm
-          cache-dependency-path: ${{ env.BUILD_PATH }}//pnpm-lock.yaml
-      - name: Install pnpm
-        run: npm install -g pnpm
-      - name: Verify pnpm installation
-        run: pnpm --version
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Install project dependencies
+        run: pnpm install
+        working-directory: ${{ env.BUILD_PATH }}
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/pnpm-lock.yaml" ]; then
+            echo "manager=pnpm" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=pnpm" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
 
   deploy:
     environment:
